default_stages: [pre-commit, pre-push]
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-toml
    -   id: detect-private-key
    -   id: mixed-line-ending
    -   id: pretty-format-json
        args: [--autofix, --no-sort-keys]
        exclude: tests(/\w*)*/functional/|tests/input|tests(/.*)+/conftest.py|doc/data/messages|tests(/\w*)*data/

#-   repo: https://github.com/asottile/pyupgrade
#    rev: v3.16.0
#    hooks:
#    -   id: pyupgrade

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        exclude: tests(/\w*)*/functional/|tests/input|tests(/.*)+/conftest.py|doc/data/messages|tests(/\w*)*data/

-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.13.0
    hooks:
    -   id: reorder-python-imports
        args: [--py39-plus, --add-import, 'from __future__ import annotations']
        exclude: tests(/\w*)*/functional/|tests/input|tests(/.*)+/conftest.py|doc/data/messages|tests(/\w*)*data/

#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.10.1
#    hooks:
#    -   id: mypy
#        additional_dependencies: [textual, rich, pydantic, ollama, docker, types-beautifulsoup4, types-requests, types-pytz, types-simplejson, typing-extensions, asyncio, humanize, argparse, python-dotenv]
#        exclude: tests(/\w*)*/functional/|tests/input|tests(/.*)+/conftest.py|doc/data/messages|tests(/\w*)*data/

- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: make
      language: system
      pass_filenames: false
      args:
        [typecheck]
      exclude: tests(/\w*)*/functional/|tests/input|tests(/\w*)*data/|doc/

- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: make
      language: system
      pass_filenames: false
      args:
        [lint]
      exclude: tests(/\w*)*/functional/|tests/input|tests(/\w*)*data/|doc/
