default_stages: [pre-commit, pre-push]
default_language_version:
    python: python3.11
fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: check-docstring-first
    -   id: check-toml
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
        args: [--autofix, --no-sort-keys]
        exclude: tests(/\w*)*/functional/|tests/input|tests(/.*)+/conftest.py|doc/data/messages|tests(/\w*)*data/|Pipfile.lock

#-   repo: https://github.com/asottile/reorder-python-imports
#    rev: v3.13.0
#    hooks:
#    -   id: reorder-python-imports
#        args: [--py39-plus, --add-import, "from __future__ import annotations"]
#        exclude: tests(/\w*)*/functional/|tests/input|tests(/.*)+/conftest.py|doc/data/messages|tests(/\w*)*data/

-   repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    -   id: black
        args: [-t, py310, -t, py311, -t, py312]
        exclude: tests(/\w*)*/functional/|tests/input|tests(/.*)+/conftest.py|doc/data/messages|tests(/\w*)*data/

#- repo: local
#  hooks:
#    - id: mypy
#      name: mypy
#      entry: make
#      language: system
#      pass_filenames: false
#      args:
#        [typecheck]
#      exclude: tests(/\w*)*/functional/|tests/input|tests(/\w*)*data/|doc/

#- repo: https://github.com/RobertCraigie/pyright-python
#  rev: v1.1.376
#  hooks:
#  - id: pyright

- repo: local
  hooks:
    - id: pyright
      name: pyright
      entry: make
      language: system
      pass_filenames: false
      args:
        [typecheck]
      exclude: tests(/\w*)*/functional/|tests/input|tests(/\w*)*data/|doc/

- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: make
      language: system
      pass_filenames: false
      args:
        [lint]
      exclude: tests(/\w*)*/functional/|tests/input|tests(/\w*)*data/|doc/
