default_stages: [pre-commit, pre-push]
default_language_version:
    python: python3.11
fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: check-docstring-first
    -   id: check-toml
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
        args: [--autofix, --no-sort-keys]
        exclude: tests(/\w*)*/functional/|tests/input|tests(/.*)+/conftest.py|doc/data/messages|tests(/\w*)*data/|Pipfile.lock|output/.*

- repo: local
  hooks:
    - id: pyright
      name: pyright
      entry: make
      language: system
      pass_filenames: false
      args:
        [typecheck]
      exclude: tests(/\w*)*/functional/|tests/input|tests(/\w*)*data/|doc/|output/.*

- repo: local
  hooks:
    - id: format
      name: format
      entry: make
      language: system
      pass_filenames: false
      args:
        [format]
      exclude: tests(/\w*)*/functional/|tests/input|tests(/\w*)*data/|doc/|output/.*

- repo: local
  hooks:
    - id: lint
      name: lint
      entry: make
      language: system
      pass_filenames: false
      args:
        [lint]
      exclude: tests(/\w*)*/functional/|tests/input|tests(/\w*)*data/|doc/|output/.*
